services:
  okoh-postgres:
    container_name: landing-page
    image: postgres
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    