export const urls = {
  home: "/",
  parents:"parents",
  about_gradely: "https://gradely.ng/about",
  blog: "https://gradely.ng/blog",
  login: "https://app.gradely.co/auth/login",
  become_a_tutor: "https://gradely.co/tutor_signup.html",
  download_apps: "",
  start_learning: "https://app.gradely.co/auth/signup-lander",
  for_schools: "https://gradely.co/for-schools/",
  for_parents: "https://gradely.ng/pages/tutoring",
  for_teachers: "https://app.gradely.co/auth/signup-teacher",
  tutoring: "https://gradely.ng/tutoring",
  learn: "",
  contact_us: "https://gradely.ng/contact-us",
  help_center: "https://gradely.ng/help-centre",
  privacy: "https://gradely.ng/privacy-policy",
  tac: "https://gradely.ng/terms",
  contact_email: "mailto:support@gradely.ng",
  contact_email2:"mailto:hello@gradely.co",
  contact_phone_uk: "tel:+4407388263241",
  contact_whatsapp: "https://wa.me/2348100598268",
  contact_phone_ng: "tel:+2348100598268",
  facebook: "https://www.facebook.com/gradelyng",
  instagram: "https://www.instagram.com/gradelyng",
  twitter: "https://www.twitter.com/gradelyng",
  youtube: "https://www.youtube.com/channel/UCsiHe1Qm8SZ_8LD5zkEY1Rw/",
  linked_in: "https://www.linkedin.com/company/gradelyng/about/",
};
